version: '3'

# Only for development environment !!!

services:
  payload:
    image: node:20-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      - postgres
      - minio
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:17.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: payload_cms
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: portfolio_blog

  minio:
    restart: always
    image: minio/minio
    command: minio server /data --console-address :9001 --address :9000
    volumes:
      - s3-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/payload-content-bucket;
      /usr/bin/mc anonymous set public myminio/payload-content-bucket;
      /usr/bin/mc admin accesskey create myminio/ --access-key myuseraccesskey --secret-key myusersecretkey --description "Access key for testing"
      exit 0;
      "

volumes:
  data:
  pgdata:
  node_modules:
  s3-data:
