import Footer from '@/modules/common/components/Footer'
import Menu from '@/modules/common/components/Menu'

import './globals.css'
import styles from './layout.module.css'

import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { TranslationSwitch } from '@/modules/common/components/TranslationSwitch'

export const metadata = {
  title: 'EP: Cyber Blog ⚡',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: 'en' | 'pl' }
}) {
  if (!routing.locales.includes(locale as 'pl' | 'en')) {
    notFound()
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <head>
          <link rel="shortcut icon" href="/icons/favicon.ico" />
          <link rel="shortcut icon" href="/icons/favicon.svg" type="image/svg+xml" />
        </head>
        <body className={styles.mainLayout}>
          <Menu className={styles.mainNav}></Menu>
          <main className={styles.mainLayoutContent}>{children}</main>
          <Footer></Footer>
          <TranslationSwitch className={styles.translationSwitch}></TranslationSwitch>
        </body>
      </NextIntlClientProvider>
    </html>
  )
}
