import Footer from '@/modules/common/components/Footer'
import Menu from '@/modules/common/components/Menu'

import './globals.css'
import styles from './layout.module.css'

export const metadata = {
  title: 'EP: Cyber Blog ⚡',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/icons/favicon.ico" />
        <link rel="shortcut icon" href="/icons/favicon.svg" type="image/svg+xml" />
      </head>
      <body className={styles.mainLayout}>
        <Menu className={styles.mainNav}></Menu>
        <main className={styles.mainLayoutContent}>{children}</main>
        <Footer></Footer>
      </body>
    </html>
  )
}
